[package]
name = "aoe4-vill-warning"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.28.1"
egui = "0.28.1"
egui_extras = { version = "0.28.1", features = ["all_loaders"] }
geo = "0.28.0"
image = "0.25.2"
imageproc = "0.25.0"
rodio = "0.19.0"
xcap = "0.0.11"
